import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('diamonds.csv')
print("Dataset Info:")
print(df.info())
print("\nFirst 5 rows:")
print(df.head())
print("\nMissing values:")
print(df.isnull().sum())
fig, axes = plt.subplots(1, 2, figsize=(12, 5))
axes[0].hist(df['price'], bins=50, edgecolor='black', alpha=0.7, color='skyblue')
axes[0].set_title('Distribution of Diamond Prices')
axes[0].set_xlabel('Price ($)')
axes[0].set_ylabel('Frequency')
axes[1].scatter(df['carat'], df['price'], alpha=0.3, s=1, color='coral')
axes[1].set_title('Carat vs Price')
axes[1].set_xlabel('Carat')
axes[1].set_ylabel('Price ($)')
plt.tight_layout()
plt.show()