import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('Titanic-Dataset.csv')
print("Dataset Info:")
print(df.info())
print("\nFirst 5 rows:")
print(df.head())
print("\nMissing values:")
print(df.isnull().sum())
fig, axes = plt.subplots(1, 2, figsize=(12, 5))
axes[0].hist(df['Age'].dropna(), bins=30, edgecolor='black', alpha=0.7, color='skyblue')
axes[0].set_title('Distribution of Passenger Ages')
axes[0].set_xlabel('Age')
axes[0].set_ylabel('Frequency')
axes[1].bar(['Died', 'Survived'], df['Survived'].value_counts().values, color=['red', 'green'], edgecolor='black')
axes[1].set_title('Survival Count')
axes[1].set_ylabel('Count')
plt.tight_layout()
plt.show()